CREATE TABLE Channel
(
	ChannelId			BIGINT		IDENTITY(1, 1)			NOT NULL		CONSTRAINT pkChannel PRIMARY KEY WITH FILLFACTOR = 80,
	ChannelName			VARCHAR(50)							NOT NULL		CONSTRAINT ukChannel UNIQUE,
	CreateDate			DATETIME	DEFAULT(GETDATE())		NOT NULL,
	Active				BIT			DEFAULT(1)				NOT NULL
)
GO
